### PR TITLE
jd-core upgrade to v1.1.3

### PR DESCRIPTION
**Pull request by jpstotz**
This pull request updates the jd-core decompiler implementation to the latest stable release 1.1.3.

The included jd-core jar file is the one shown for download at it's GitHub release page:
https://github.com/java-decompiler/jd-core/releases/tag/v1.1.3

I am open for comments and critics. The large commented-out section in JDCoreDecompiler.java is because I wasn't able to determine for what reason the line numbers in comments were always removed from the generated source code (makes it hard to test this feature if the line numbers are always stripped off the code).

### CODE REVIEW

**Comment by jpstotz** [comment]
@pbi-qfs @RobertZenz Happy new year to both of you.
Is there anything left I can do to make the review easier to you both?

**Comment by RobertZenz** [comment]
@jpstotz No, sorry, you can't do anything to make this go any faster.

I can only verify this against an Eclipse 4.7 with Java 8 currently, as I do not have another setup. I promise to look at it on the weekend.

**Comment by RobertZenz** [comment]
Would you mind undoing the whitespace/formatting changes (in the commits, not as extra one)? I know that style is...odd, we've got #19 for that. Here it introduces quite some noise to the changes.

**Comment by jpstotz** [comment]
@RobertZenz Sorry I wasn't aware of the formatting changes. Those changes are cause caused because I always use the default code formatter that has been configured in each Java project. It seems like for most of the ecd plugin projects the formatter was not correctly set (or my Eclipse version was not able to recognize it as valid formatter profile) which I did not recognize and therefore applied the wrong code format. 

Can you please point me which project contains the "correct source code formatter" to use? Because when I compare the `org.eclipse.core.resources.prefs` files from each project they all look a bit different.
I tried to export the unmanaged code style profile "birt" to apply it on the other projects but Eclipse just created ab empty xml file. Hence I would assume something is wrong with that code style.

Is there a reason why #19 has not been applied yet? For some one with write access to the repo this a task of may be two minutes. From my perspective you just have to decide which formatting profile to use, set it on each ecd code project and finally [apply it on all ecd projects](https://stackoverflow.com/a/5133787/150978).

**Comment by RobertZenz** [comment]
Can you please try again with [with this birt profile](https://github.com/ecd-plugin/ecd/files/5826210/birt.xml.txt)? I've saved and exported it through Eclipse (the one I have available, that is, the latest is not working on my machine). 

 > Is there a reason why #19 has not been applied yet? For some one with write access to the repo this a task of may be two minutes. From my perspective you just have to decide which formatting profile to use, set it on each ecd code project and finally apply it on all ecd projects.

Yes, technically. We kept it initially to make it possible to apply upstream patches easier, but as it turns out, there are no upstream patches (and Pascal and me wouldn't have time to track upstream anyway, as it turns out). So you might as well as do it, if you feel like it (as an extra MR without any other changes). Be warned, though, it *will* break your merge request if applied before.

The MR looks good to me, need to test it. As said, I only got a JDK8, though.

**Comment by jpstotz** [comment]
@RobertZenz Thanks, that profile works. I applied to to app files changed in this PR. 
Doing so reverted a lot of style changes but unfortunately not all. 

Regarding the new code style changes for the overall ecp project I will prepare the changes in a new PR, once this PR has been completed.

**Comment by RobertZenz** [comment]
Sorry for the extremely long delay. I've verified that it decompiles classes on Eclipse 2020-12/Java8. So I guess that's good enough.

Again, sorry for the extreme delay, I do not have a workflow anymore for developing this plugin and I'm currently otherwise occupied for what it's worth. In accordance with @pbi-qfs you'll be receiving maintainer privileges to make sure that your contributions will not go to waste or otherwise just linger around any further.

However, feel free to contact me if you have questions or other issues.

**Comment by jpstotz** [comment]
@RobertZenz Thanks for the invitation. Yes, this PR took some days however to be honest in this case I never had the feeling that it would be in a stalled or even blocked state. 

This PR got step-by-step to it's final state and that people are busy with a lot of other things and projects is just life. What I don't like is getting the feeling like running into walls that block me for strange and incomprehensible reasons. But I never got this feeling in this case :)

**Comment by pbi-qfs** [comment]
@jpstotz Great, thanks for taking the initiative. You should now also be able to push to the update site to upload a new release containing your improvements.

**Comment by jpstotz** [comment]
@pbi-qfs Hi Pascal. Thanks for your trust in me. 
I assume that the update project is generated using the maven tycho plugin. I have not yet worked much with that plugin but I am sure I figure it out or do you remember the command you used for updating "update p2 repo"?

**Pull request merged**
